.global method_System_Byte__RETEND_Testing2_ExceptionMethods_DECLEND_get_BasePointer_NAMEEND___
.global method_System_Void_RETEND_Testing2_ExceptionMethods_DECLEND_set_BasePointer_NAMEEND__System_Byte__

.text

.ent method_System_Byte__RETEND_Testing2_ExceptionMethods_DECLEND_get_BasePointer_NAMEEND___
method_System_Byte__RETEND_Testing2_ExceptionMethods_DECLEND_get_BasePointer_NAMEEND___:
sw $fp, 0($sp)
j $ra
.end method_System_Byte__RETEND_Testing2_ExceptionMethods_DECLEND_get_BasePointer_NAMEEND___

.ent method_System_Void_RETEND_Testing2_ExceptionMethods_DECLEND_set_BasePointer_NAMEEND__System_Byte__
method_System_Void_RETEND_Testing2_ExceptionMethods_DECLEND_set_BasePointer_NAMEEND__System_Byte__:
lw $fp, 0($sp)
j $ra
.end method_System_Void_RETEND_Testing2_ExceptionMethods_DECLEND_set_BasePointer_NAMEEND__System_Byte__
