.global method_System_Object_RETEND_Testing1_Utilities_ObjectUtilities_DECLEND_GetObject_NAMEEND__System_Void__

.text

.ent method_System_Object_RETEND_Testing1_Utilities_ObjectUtilities_DECLEND_GetObject_NAMEEND__System_Void__

method_System_Object_RETEND_Testing1_Utilities_ObjectUtilities_DECLEND_GetObject_NAMEEND__System_Void__:
lw $t0, 4($sp)
sw $t0, 0($sp)
j $ra

.end method_System_Object_RETEND_Testing1_Utilities_ObjectUtilities_DECLEND_GetObject_NAMEEND__System_Void__
