BITS 32

SECTION .text

GLOBAL method_System_Void_RETEND_Kernel_Devices_CPUs_CPUx86_32_DECLEND_Halt_NAMEEND___:function

method_System_Void_RETEND_Kernel_Devices_CPUs_CPUx86_32_DECLEND_Halt_NAMEEND___:
hlt
ret
